# Generated by Django 6.0.4 on 2026-04-10 08:08

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kafedra nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dept_logos/', verbose_name='Kafedra logotipi')),
                ('description', models.TextField(blank=True, verbose_name='Kafedra haqida qisqacha')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Oson'), ('MEDIUM', "O'rtacha"), ('HARD', 'Qiyin')], default='MEDIUM', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('KURSANT', 'Kursant'), ('INSTRUCTOR', 'Instruktor'), ('DEPT_HEAD', "Kafedra Boshlig'i"), ('INST_HEAD', "Institut Boshlig'i")], default='KURSANT', max_length=21, verbose_name='Foydalanuvchi Roli')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='Harbiy unvon')),
                ('is_starshina', models.BooleanField(default=False, verbose_name='Starshina statusi')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.department', verbose_name='Tegishli kafedrasi')),
                ('teaches_in', models.ManyToManyField(blank=True, related_name='instructors_list', to='core.department', verbose_name='Dars beradigan kafedralari')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Resurs nomi')),
                ('file', models.FileField(upload_to='resources/%Y/%m/', validators=[core.models.validate_file_size], verbose_name='Fayl')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Kitob'), ('doc', 'Word hujjat'), ('video', 'Video darslik'), ('audio', 'Audio darslik'), ('ppt', 'Prezentatsiya')], default='pdf', max_length=10, verbose_name='Fayl turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resource_covers/', verbose_name='Muqova')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_resources', to='core.department')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/%Y/%m/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resource_covers/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Kitob'), ('doc', 'Word hujjat'), ('video', 'Video darslik'), ('audio', 'Audio darslik'), ('ppt', 'Prezentatsiya')], default='pdf', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Dars mavzusi')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Dars matni (Konspekt)')),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons/videos/', validators=[core.models.validate_video_size])),
                ('presentation', models.FileField(blank=True, null=True, upload_to='lessons/files/', validators=[core.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('target_departments', models.ManyToManyField(related_name='visible_lessons', to='core.department', verbose_name="Ko'ra oladigan kafedralar")),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Xabar mavzusi')),
                ('body', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_official_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_official_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rasmiy Xabar',
                'verbose_name_plural': 'Rasmiy Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(default=15, help_text='Test vaqti (minut)')),
                ('pass_percentage', models.PositiveIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('is_passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('description', models.TextField(blank=True, verbose_name='Fan haqida')),
                ('available_in_departments', models.ManyToManyField(help_text="Tarix fanini qaysi kafedralar ko'ra olishini belgilang", related_name='subjects', to='core.department', verbose_name="Ushbu fan o'qitiladigan kafedralar")),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_subjects', to='core.department', verbose_name='Asosiy kafedra (Eski)')),
                ('instructors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'INSTRUCTOR'}, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul o'qituvchilar")),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.subject', verbose_name="Mas'ul Fan"),
        ),
    ]
