# Generated by Django 6.0.3 on 2026-04-01 05:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_content_alter_lesson_target_departments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Dars matni (Konspekt)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/', validators=[core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.subject', verbose_name="Mas'ul Fan"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='target_departments',
            field=models.ManyToManyField(related_name='visible_lessons', to='core.department', verbose_name="Ko'ra oladigan kafedralar"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', validators=[core.models.validate_video_size]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.department', verbose_name='Kafedra'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='instructors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'INSTRUCTOR'}, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul o'qituvchilar"),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.department', verbose_name='Tegishli kafedrasi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('KURSANT', 'Kursant'), ('INSTRUCTOR', 'Instruktor'), ('COMMANDER', 'Komandir')], default='KURSANT', max_length=20, verbose_name='Roli'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teaches_in',
            field=models.ManyToManyField(blank=True, related_name='instructors_list', to='core.department', verbose_name='Dars beradigan kafedralari'),
        ),
    ]
