# Generated by Django 6.0.3 on 2026-04-07 05:34

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_choice_quiz_question_quiz_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Resurs nomi')),
                ('file', models.FileField(upload_to='resources/%Y/%m/', validators=[core.models.validate_file_size], verbose_name='Fayl')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Hujjat'), ('doc', 'Word/Excel'), ('ppt', 'Taqdimot'), ('other', 'Boshqa')], default='pdf', max_length=10, verbose_name='Fayl turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_resources', to='core.department', verbose_name='Qaysi kafedra uchun')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yuklovchi')),
            ],
            options={
                'verbose_name': 'Kafedra resursi',
                'verbose_name_plural': 'Kafedra resurslari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Resurs nomi')),
                ('file', models.FileField(upload_to='resources/%Y/%m/', validators=[core.models.validate_file_size], verbose_name='Fayl')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Hujjat'), ('doc', 'Word/Excel'), ('ppt', 'Taqdimot'), ('other', 'Boshqa')], default='pdf', max_length=10, verbose_name='Fayl turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Qisqacha mazmuni')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yuklovchi')),
            ],
            options={
                'verbose_name': 'Umumiy adabiyot',
                'verbose_name_plural': 'Umumiy adabiyotlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
