# Generated by Django 6.0.3 on 2026-04-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departmentresource_globallibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentresource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resource_covers/'),
        ),
    ]
