# Generated by Django 6.0.3 on 2026-04-07 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_departmentresource_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globallibrary',
            options={},
        ),
        migrations.AddField(
            model_name='globallibrary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resource_covers/'),
        ),
        migrations.AlterField(
            model_name='globallibrary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globallibrary',
            name='file',
            field=models.FileField(upload_to='resources/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='globallibrary',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='globallibrary',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globallibrary',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
