# Generated by Django 6.0.3 on 2026-04-07 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_globallibrary_options_globallibrary_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentresource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AddField(
            model_name='subject',
            name='available_in_departments',
            field=models.ManyToManyField(help_text="Tarix fanini qaysi kafedralar ko'ra olishini belgilang", related_name='subjects', to='core.department', verbose_name="Ushbu fan o'qitiladigan kafedralar"),
        ),
        migrations.AlterField(
            model_name='departmentresource',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_resources', to='core.department'),
        ),
        migrations.AlterField(
            model_name='departmentresource',
            name='file_type',
            field=models.CharField(default='pdf', max_length=10, verbose_name='Fayl turi'),
        ),
        migrations.AlterField(
            model_name='departmentresource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=15, help_text='Test vaqti (minut)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_subjects', to='core.department', verbose_name='Asosiy kafedra (Eski)'),
        ),
    ]
