# Generated by Django 6.0.3 on 2026-04-08 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_departmentresource_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentresource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Kitob'), ('doc', 'Word hujjat'), ('video', 'Video darslik'), ('audio', 'Audio darslik'), ('ppt', 'Prezentatsiya')], default='pdf', max_length=10, verbose_name='Fayl turi'),
        ),
        migrations.AlterField(
            model_name='departmentresource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resource_covers/', verbose_name='Muqova'),
        ),
        migrations.AlterField(
            model_name='globallibrary',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Kitob'), ('doc', 'Word hujjat'), ('video', 'Video darslik'), ('audio', 'Audio darslik'), ('ppt', 'Prezentatsiya')], default='pdf', max_length=10),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
